Detect `Thread.Sleep` and Win32 `Sleep/SleepEx` as blocking objects
goldshtn/msos pull request #66
Opened 2017-01-27 13:35 UTC by Pavel-Durov

Detecting `Thread.Sleep` and Win32 `Sleep/SleepEx` as blocking objects by inspecting for NtDelayExecution function. Same flow  as we do with CriticalSections

2017-01-27 13:59 UTC, goldshtn requested changes

2017-01-27 13:59 UTC, goldshtn commented on msos/StackWalker.cs
> +            var awaitMs = ((-1) * largeInt.QuadPart) / 10000;
`((-1) * something)` is really a very verbose way of saying `-something`.

2017-01-27 13:59 UTC, goldshtn commented on msos/StackWalker.cs
> +                throw new Exception($"Error reading structure data from address: {address}");
Would be nice to format the address as hex here.

2017-01-27 13:59 UTC, goldshtn commented on msos/WaitChains.cs
> +                                : blockingObject.Reason.ToString();
I don't understand why this special treatment is needed here. Why can't the blocking object itself do its own formatting? This kind of if-else logic is really unclean.

2017-01-27 14:39 UTC, Pavel-Durov commented on msos/StackWalker.cs
> +            var awaitMs = ((-1) * largeInt.QuadPart) / 10000;
changed

2017-01-27 14:39 UTC, Pavel-Durov commented on msos/StackWalker.cs
> +                throw new Exception($"Error reading structure data from address: {address}");
done

2017-01-27 14:42 UTC, Pavel-Durov commented on msos/WaitChains.cs
> +                                : blockingObject.Reason.ToString();
I added ReasonDescription property in UnifiedBlockingObject class, previously onlyReason property (which is an UnifiedBlockingReason enum) was printed.

2017-05-03 11:37 UTC, Pavel-Durov commented
@goldshtn Is there anything else I need to address in this PR? I think I went over all of the requested changes :)

2017-05-03 11:53 UTC, goldshtn requested changes
Just a couple of minor changes and this is good to go.

2017-05-03 11:53 UTC, goldshtn commented on msos/MixedStack.cs
> +            ReasonDescription = $"MsTimeout : {msTimeout}";
Please change to read "Sleep with timeout: 766ms" if there is a timeout, or to "Sleep with no timeout" if the timeout is infinite.

2017-05-03 11:53 UTC, goldshtn commented on msos/NativeStructs.cs
> +        public struct LARGE_INTEGER
Why is this needed? It's basically `Int64`.

2017-05-03 12:32 UTC, merged